### ISSUE TITLE
Gossip/dialogue skipping

### ISSUE THREAD

**Issue by Vartou** [Saaappi/HelpMePlay#67] opened 2023-03-29 18:47 UTC
I've been having an issue as of yesterday and today where dialogue options are no longer skipping for me with the addon where on my last character I levelled it was skipping most of my dialogue unsure if there's something I forgot to check off on my addon or if it's stopped working all of a sudden? sorry if theres a lack of information or anything never used this website and the curseforge page there was a comment saying you didnt check it often.

**Comment by Saaappi** [comment] 2023-03-30 19:21
@Vartou Have you updated to 2.0.19?

**Comment by Saaappi** [comment] 2023-03-30 21:58
I've found the problem but the cause is unknown. I'm investigating and I'll deploy a fix ASAP.

**Comment by Saaappi** [comment] 2023-03-30 22:08
Fixed in the next update, which will be live later today.

**Closed as completed by Saaappi** 2023-03-30 22:08 UTC
